### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [SamaAxl/ExposicionSomos#1]
Muy bien, jóvenes. Me agrada el tema que usaron.

Les adjunto algunas modificaciones para que realicen:
- Tienen varias faltas de ortografía en la página principal, les encargo que lo corrijan.
- Se ve bien el fondo que colocaron, pero en ocasiones se batalla para leer el texto que colocaron.
- Agreguen un párrafo inventado sobre la historia de su empresa.

Espero su respuesta.

**Comment by SamaAxl** [comment]
Cambio aplicado.

**Comment by SamaAxl** [comment]
Cambio aplicado.

**Comment by CarlosRubioTNM** [comment]
Excelente. Bien hecho, jóvenes. Cierro el issue.
